### PR TITLE
only return future bookings

### PR DESCRIPTION
**Pull request by abdulfaizp**
line 552. filter the bookings to be only future bookings, so users wont delete the past bookings.
@xoneco have a look please, since its django database api mods

### CODE REVIEW

**Comment by abdulfaizp** [comment]
@xoneco that's still possible with a combining the end_time and todays date. I will write a custom filter, dont merge this yet, I will modify it

**Comment by ChristopherHammond13** [comment]
Do we know that this works perfectly? If so I can merge it in now. Apologies for not seeing this PR earlier!

**Comment by abdulfaizp** [comment]
@ChristopherHammond13 ooops sorry! never got to writing the actual script for this. This will work, but not in the way wil wanted :D

**Comment by ChristopherHammond13** [comment]
Should this have been merged, @jermenkoo? I spoke to @abdulfaizp and he said it wasn't ready yet? If @abdulfaizp and @xoneco are happy then I'll delete the branch and pull this into production.

**Comment by jermenkoo** [comment]
@ChristopherHammond13 yes, as @abdulfaizp said on slack "It can be merged" :)

**Pull request merged**
